name: Verilog

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  ubuntu:
    runs-on: ubuntu-20.04

    steps:
    - name: deps
      run: sudo apt install iverilog

    - name: build
      run: make
